### ISSUE TITLE
Module name needs to be updated

### ISSUE THREAD

**Issue by yudistrange** [loggysh/loggy#42]
These are probably minor issues, but worth fixing for consistency.

The go mod file is still referencing the older github repo name.
https://github.com/loggysh/loggy/blob/7cff450db475ae8730af2d90885f6792a4dc7eb1/go.mod#L1

The same can be done here as well:
https://github.com/loggysh/loggy/blob/7cff450db475ae8730af2d90885f6792a4dc7eb1/loggy/loggy.proto#L7

**Comment by imran0101** [comment]
@yudistrange Should switching to "github.com/loggysh/loggy" resolve this ?

**Comment by yudistrange** [comment]
Yeah. That's the fix. 

We will also need to change the `Makefile`
https://github.com/loggysh/loggy/blob/7cff450db475ae8730af2d90885f6792a4dc7eb1/Makefile#L10
Here we are using the older module name for the generated protobufs.
